import path from 'path';

import { Ios } from '@expo/eas-build-job';
import fs from 'fs-extra';

import { BuildContext } from '../context';

export async function deleteXcodeEnvLocalIfExistsAsync(
  ctx: BuildContext<Ios.Job>
): Promise<boolean> {
  const xcodeEnvLocalPath = path.join(ctx.reactNativeProjectDirectory, 'ios', '.xcode.env.local');
  if (!(await fs.pathExists(xcodeEnvLocalPath))) {
    return false;
  } else {
    ctx.logger.warn(
      `Detected .xcode.env.local uploaded to EAS Build. Make sure this file is not committed to the repository. If you're using the .easignore file, add the file there. .xcode.env.local will be deleted and regenerated by "pod install".`
    );
    await fs.remove(xcodeEnvLocalPath);
    return true;
  }
}
