coverage:
  round: up
  precision: 2
  range: 30..100
  status:
    patch: false
    project:
      steps:
        informational: true
        paths:
          - packages/steps

ignore:
  - packages/steps/**/__tests__/**/*.ts
  - packages/steps/src/scripts/runCustomFunction.ts
