export enum BuildPhase {
  UNKNOWN = 'UNKNOWN',
  BUILDER_INFO = 'BUILDER_INFO',
  READ_APP_CONFIG = 'READ_APP_CONFIG',
  SET_UP_BUILD_ENVIRONMENT = 'SET_UP_BUILD_ENVIRONMENT',
  START_BUILD = 'START_BUILD',
  INSTALL_CUSTOM_TOOLS = 'INSTALL_CUSTOM_TOOLS',
  PREPARE_PROJECT = 'PREPARE_PROJECT',
  RESTORE_CACHE = 'RESTORE_CACHE',
  INSTALL_DEPENDENCIES = 'INSTALL_DEPENDENCIES',
  PREBUILD = 'PREBUILD',
  PREPARE_CREDENTIALS = 'PREPARE_CREDENTIALS',
  CONFIGURE_EXPO_UPDATES = 'CONFIGURE_EXPO_UPDATES',
  SAVE_CACHE = 'SAVE_CACHE',
  UPLOAD_ARTIFACTS = 'UPLOAD_ARTIFACTS',
  PREPARE_ARTIFACTS = 'PREPARE_ARTIFACTS',
  CLEAN_UP_CREDENTIALS = 'CLEAN_UP_CREDENTIALS',
  COMPLETE_BUILD = 'COMPLETE_BUILD',
  FAIL_BUILD = 'FAIL_BUILD',

  // ANDROID
  FIX_GRADLEW = 'FIX_GRADLEW',
  RUN_GRADLEW = 'RUN_GRADLEW',

  // IOS
  INSTALL_PODS = 'INSTALL_PODS',
  CONFIGURE_XCODE_PROJECT = 'CONFIGURE_XCODE_PROJECT',
  RUN_FASTLANE = 'RUN_FASTLANE',

  // HOOKS
  PRE_INSTALL_HOOK = 'PRE_INSTALL_HOOK',
  POST_INSTALL_HOOK = 'POST_INSTALL_HOOK',
  PRE_UPLOAD_ARTIFACTS_HOOK = 'PRE_UPLOAD_ARTIFACTS_HOOK',
}

export enum LogMarker {
  START_PHASE = 'START_PHASE',
  END_PHASE = 'END_PHASE',
}
