name: Create and Build Public Cache App (All Platforms)

on:
  workflow_dispatch: {}

jobs:
  create-and-build-android:
    name: Create public-cache app and build Android
    runs_on: linux-medium
    env:
      EAS_USE_CACHE: "1"
      EAS_SAVE_CACHE: "1"
      EAS_BUILD_RUNNER: "eas-build"
    steps:
      - name: Install dependencies
        run: yarn install

      - name: Create fresh expo app
        run: |
          # Create a new directory for the public-cache app
          mkdir -p ../public-cache
          cd ../public-cache

          # Initialize a new Expo app
          npx create-expo-app@latest . --template blank --no-install

          # Update app.json with the correct name and slug
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "build-cache",
              "slug": "build-cache",
              "owner": "expo",
              "version": "1.0.0",
              "orientation": "portrait",
              "icon": "./assets/icon.png",
              "userInterfaceStyle": "light",
              "newArchEnabled": true,
              "splash": {
                "image": "./assets/splash-icon.png",
                "resizeMode": "contain",
                "backgroundColor": "#ffffff"
              },
              "ios": {
                "supportsTablet": true,
                "bundleIdentifier": "com.yourcompany.publiccache"
              },
              "android": {
                "adaptiveIcon": {
                  "foregroundImage": "./assets/adaptive-icon.png",
                  "backgroundColor": "#ffffff"
                },
                "package": "com.yourcompany.publiccache"
              },
              "web": {
                "favicon": "./assets/favicon.png"
              },
              "extra": {
                "eas": {
                  "projectId": "38453199-7b7d-4338-a6d1-9fb21f48ab0d"
                }
              }
            }
          }
          EOF

          # Install dependencies
          yarn install

      - name: Create EAS build configuration
        run: |
          cd ../public-cache
          cat > eas.json << 'EOF'
          {
            "cli": {
              "version": ">= 13.2.2"
            },
            "build": {
              "development": {
                "developmentClient": true,
                "distribution": "internal",
                "android": {
                  "buildType": "apk"
                }
              },
              "preview": {
                "distribution": "internal",
                "android": {
                  "buildType": "apk",
                  "gradleCommand": ":app:assembleDebug",
                  "withoutCredentials": true,
                },
                "env": {
                  "EAS_BUILD_RUNNER": "eas-build",
                  "EAS_USE_CACHE": "1",
                  "EAS_SAVE_CACHE": "1",
                  "EAS_RESTORE_CACHE": "0",
                  "ANDROID_CCACHE": "/usr/bin/ccache"
                }
              },
              "production": {}
            },
            "submit": {
              "production": {}
            }
          }
          EOF

      - name: Run Local EAS Build (Android)
        run: |
          sudo apt-get update && sudo apt-get install -y ccache
          cd ../public-cache
          EAS_BUILD_RUNNER=eas-build EAS_USE_CACHE=1 EAS_SAVE_CACHE=1 npx eas-cli build --platform android --profile preview --local --non-interactive

      - name: Show cache stats
        run: |
          command -v ccache
          ccache --show-stats -v

      - name: Save ccache
        uses: eas/save_cache
        with:
          key: public-android-cache-${{ job.sdkVersion }}
          path: /home/expo/.cache/ccache

      - name: Run Local EAS Build (Android) again
        run: |
          cd ../public-cache
          EAS_BUILD_RUNNER=eas-build EAS_USE_CACHE=1 EAS_SAVE_CACHE=1 npx eas-cli build --platform android --profile preview --local --non-interactive

      - name: Show cache stats
        run: |
          command -v ccache
          ccache --show-stats -v

  create-and-build-ios:
    name: Create public-cache app and build iOS
    runs_on: macos-medium
    env:
      EAS_USE_CACHE: "1"
      EAS_SAVE_CACHE: "1"
      EAS_BUILD_RUNNER: "eas-build"
    steps:
      - name: Install dependencies
        run: yarn install

      - name: Create fresh expo app
        run: |
          # Create a new directory for the public-cache app
          mkdir -p ../public-cache
          cd ../public-cache

          # Initialize a new Expo app
          npx create-expo-app@latest . --template blank --no-install

          # Update app.json with the correct name and slug
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "build-cache",
              "slug": "build-cache",
              "owner": "expo",
              "version": "1.0.0",
              "orientation": "portrait",
              "icon": "./assets/icon.png",
              "userInterfaceStyle": "light",
              "newArchEnabled": true,
              "splash": {
                "image": "./assets/splash-icon.png",
                "resizeMode": "contain",
                "backgroundColor": "#ffffff"
              },
              "ios": {
                "supportsTablet": true,
                "bundleIdentifier": "com.yourcompany.publiccache"
              },
              "android": {
                "adaptiveIcon": {
                  "foregroundImage": "./assets/adaptive-icon.png",
                  "backgroundColor": "#ffffff"
                },
                "package": "com.yourcompany.publiccache"
              },
              "web": {
                "favicon": "./assets/favicon.png"
              },
              "extra": {
                "eas": {
                  "projectId": "38453199-7b7d-4338-a6d1-9fb21f48ab0d"
                }
              }
            }
          }
          EOF

          # Install dependencies
          yarn install

      - name: Create EAS build configuration
        run: |
          cd ../public-cache
          cat > eas.json << 'EOF'
          {
            "cli": {
              "version": ">= 13.2.2"
            },
            "build": {
              "development": {
                "developmentClient": true,
                "distribution": "internal"
              },
              "preview": {
                "distribution": "internal",
                "ios": {
                  "simulator": true
                },
                "env": {
                  "EAS_BUILD_RUNNER": "eas-build",
                  "EAS_USE_CACHE": "1",
                  "EAS_SAVE_CACHE": "1",
                  "EAS_RESTORE_CACHE": "0",
                  "USE_CCACHE": "1",
                  "CCACHE_CPP2": "1",
                  "CCACHE_BINARY": "/opt/homebrew/bin/ccache"
                }
              },
              "production": {}
            },
            "submit": {
              "production": {}
            }
          }
          EOF

      - name: Run Local EAS Build (iOS)
        run: |
          brew install ccache
          cd ../public-cache
          EAS_BUILD_RUNNER=eas-build EAS_USE_CACHE=1 EAS_SAVE_CACHE=1 npx eas-cli build --platform ios --profile preview --local --non-interactive

      - name: Show cache stats
        run: |
          command -v ccache
          ccache --show-stats -v

      - name: Save ccache
        uses: eas/save_cache
        with:
          key: public-ios-cache-${{ job.sdkVersion }}
          path: /Users/expo/Library/Caches/ccache

      - name: Run Local EAS Build (iOS) again
        run: |
          cd ../public-cache
          EAS_BUILD_RUNNER=eas-build EAS_USE_CACHE=1 EAS_SAVE_CACHE=1 npx eas-cli build --platform ios --profile preview --local --non-interactive

      - name: Show cache stats
        run: |
          command -v ccache
          ccache --show-stats -v