name: Create and Build Public Cache App (All Platforms)

on:
  workflow_dispatch: {}

jobs:
  create-and-build-android:
    name: Create public-cache app and build Android
    runs_on: linux-large
    env:
      EAS_USE_CACHE: "1"
      EAS_SAVE_CACHE: "1"
      EAS_RESTORE_CACHE: "0"
      EAS_BUILD_RUNNER: "eas-build"
      EAS_PUBLIC_CACHE: "1"
      ANDROID_CCACHE: "/usr/bin/ccache"
    steps:
      - name: Install dependencies
        run: yarn install

      - name: Create fresh expo app
        run: |
          # Create a new directory for the public-cache app
          mkdir -p ../app
          cd ../app

          # Initialize a new Expo app
          npx create-expo-app@latest build-cache --template default

          # Update app.json with the correct name and slug
          cd build-cache
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "build-cache",
              "slug": "build-cache",
              "owner": "expo",
              "version": "1.0.0",
              "orientation": "portrait",
              "userInterfaceStyle": "light",
              "newArchEnabled": true,
              "ios": {
                "supportsTablet": true,
                "bundleIdentifier": "com.expo.buildcache"
              },
              "android": {
                "edgeToEdgeEnabled": true,
                "package": "com.expo.buildcache"
              },
              "extra": {
                "eas": {
                  "projectId": "38453199-7b7d-4338-a6d1-9fb21f48ab0d"
                }
              }
            }
          }
          EOF

          # Install dependencies
          yarn install

      - name: Create EAS build configuration
        run: |
          cd ../app/build-cache
          cat > eas.json << 'EOF'
          {
            "cli": {
              "version": ">= 13.2.2"
            },
            "build": {
              "development": {
                "developmentClient": true,
                "distribution": "internal",
                "android": {
                  "buildType": "apk"
                }
              },
              "preview": {
                "distribution": "internal",
                "android": {
                  "buildType": "apk",
                  "gradleCommand": ":app:assembleDebug",
                  "withoutCredentials": true,
                }
              },
              "production": {}
            },
            "submit": {
              "production": {}
            }
          }
          EOF

      - name: Run Local EAS Build (Android)
        run: |
          sudo apt-get update && sudo apt-get install -y ccache
          cd ../app/build-cache
          npx eas-cli build --platform android --profile preview --local --non-interactive

      - name: Show cache stats
        run: |
          command -v ccache
          ccache --show-stats -v

      # - name: Save ccache
      #   uses: eas/save_cache
      #   with:
      #     key: public-android-ccache-1.0.0-${{ hashFiles('yarn.lock') }}
      #     path: /home/expo/.cache/ccache

      - name: Run Local EAS Build (Android) again
        run: |
          cd ../app/build-cache
          npx eas-cli build --platform android --profile preview --local --non-interactive

      - name: Show cache stats
        run: |
          command -v ccache
          ccache --show-stats -v

  create-and-build-ios:
    name: Create public-cache app and build iOS
    runs_on: macos-medium
    env:
      EAS_USE_CACHE: "1"
      EAS_SAVE_CACHE: "1"
      EAS_BUILD_RUNNER: "eas-build"
      EAS_PUBLIC_CACHE: "1"
      EAS_RESTORE_CACHE: "0"
      CCACHE_BINARY: "/opt/homebrew/bin/ccache"
      CCACHE_CPP2: "1"
      USE_CCACHE: "1"
    steps:
      - name: Install dependencies
        run: yarn install

      - name: Create fresh expo app
        run: |
          # Create a new directory for the public-cache app
          mkdir -p ../app
          cd ../app

          # Initialize a new Expo app
          npx create-expo-app@latest build-cache --template default

          # Update app.json with the correct name and slug
          cd build-cache
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "build-cache",
              "slug": "build-cache",
              "owner": "expo",
              "version": "1.0.0",
              "orientation": "portrait",
              "userInterfaceStyle": "light",
              "newArchEnabled": true,
              "ios": {
                "supportsTablet": true,
                "bundleIdentifier": "com.expo.buildcache"
              },
              "android": {
                "package": "com.expo.buildcache"
              },
              "extra": {
                "eas": {
                  "projectId": "38453199-7b7d-4338-a6d1-9fb21f48ab0d"
                }
              }
            }
          }
          EOF

          # Install dependencies
          yarn install

      - name: Create EAS build configuration
        run: |
          cd ../app/build-cache
          cat > eas.json << 'EOF'
          {
            "cli": {
              "version": ">= 13.2.2"
            },
            "build": {
              "development": {
                "developmentClient": true,
                "distribution": "internal"
              },
              "preview": {
                "distribution": "internal",
                "ios": {
                  "simulator": true
                }
              },
              "production": {}
            },
            "submit": {
              "production": {}
            }
          }
          EOF

      - name: Run Local EAS Build (iOS)
        run: |
          brew install ccache
          cd ../app/build-cache
          npx eas-cli build --platform ios --profile preview --local --non-interactive

      - name: Show cache stats
        run: |
          command -v ccache
          ccache --show-stats -v

      # - name: Save ccache
      #   uses: eas/save_cache
      #   with:
      #     key: public-ios-ccache-1.0.0-${{ hashFiles('yarn.lock') }}
      #     path: /Users/expo/Library/Caches/ccache

      - name: Run Local EAS Build (iOS) again
        run: |
          cd ../app/build-cache
          npx eas-cli build --platform ios --profile preview --local --non-interactive

      - name: Show cache stats
        run: |
          command -v ccache
          ccache --show-stats -v