name: Run tests
on:
  push:
    branches: [main]
    paths:
        - 'packages/steps/**'
        - '.github/workflows/coverage.yml'
  pull_request:
    types: [opened, synchronize]
    paths:
        - 'packages/steps/**'
        - '.github/workflows/coverage.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: '"@expo/steps" code coverage'
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn build
      - run: yarn test:coverage
      - uses: codecov/codecov-action@v1
