name: Run tests
on:
  push:
    branches: [main]
    paths:
      - 'packages/steps/**'
      - '.github/workflows/coverage.yml'
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'packages/steps/**'
      - '.github/workflows/coverage.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: '"@expo/steps" code coverage'
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup ncc
        run: npm install -g @vercel/ncc
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn build
      - run: yarn test:coverage
      - uses: codecov/codecov-action@v4
